import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { PropsWithChildren } from "react";

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={clsx("antialiased ", `${roboto.className}`)}>
        <main className="bg-background w-full">{children}</main>
      </body>
    </html>
  );
}
